/**
 * pcapJitterBuffer - Read a pcap file generated by PcapDump, feed H264 RTP
 * packets through the real-time jitter buffer, and print assembled frames
 * with timestamps and NAL unit types.
 *
 * Packets are paced according to pcap record timestamps to simulate
 * real-time delivery.
 *
 * Usage: pcapJitterBuffer [-v] [-s] [-o <output.h264>] <pcap-file> [max-latency-ms]
 *   -v             verbose: print each RTP packet as it is fed to the jitter buffer
 *   -s             summary: print one line per frame (pcap time, rtp_ts, seq, size, NAL types)
 *   -o <file>      write raw Annex-B H.264 stream to <file>
 *   max-latency-ms defaults to 32
 */

#include "../src/source/Include_i.h"

#define PCAP_GLOBAL_HEADER_SIZE 24
#define PCAP_RECORD_HEADER_SIZE 16
#define PCAP_ETHERNET_HDR_SIZE  14
#define PCAP_IPV4_HDR_SIZE      20
#define PCAP_UDP_HDR_SIZE       8
#define PCAP_TRANSPORT_HDR_SIZE (PCAP_ETHERNET_HDR_SIZE + PCAP_IPV4_HDR_SIZE + PCAP_UDP_HDR_SIZE)

#define VIDEO_PT         125
#define VIDEO_CLOCK_RATE 90000

#define MAX_FRAME_SIZE (4 * 1024 * 1024)

static const char* nalUnitTypeNames[] = {
    "Unspecified",        // 0
    "NON-IDR",            // 1
    "Coded slice part A", // 2
    "Coded slice part B", // 3
    "Coded slice part C", // 4
    "IDR",                // 5
    "SEI",                // 6
    "SPS",                // 7
    "PPS",                // 8
    "AUD",                // 9
    "End of sequence",    // 10
    "End of stream",      // 11
    "Filler data",        // 12
    "SPS extension",      // 13
    "Prefix NAL unit",    // 14
    "Subset SPS",         // 15
    "DPS",                // 16
    "Reserved",           // 17
    "Reserved",           // 18
    "Coded slice aux",    // 19
    "Coded slice ext",    // 20
    "Coded slice 3D ext", // 21
    "Reserved",           // 22
    "Reserved",           // 23
    "STAP-A",             // 24
    "STAP-B",             // 25
    "MTAP16",             // 26
    "MTAP24",             // 27
    "FU-A",               // 28
    "FU-B",               // 29
    "Reserved",           // 30
    "Reserved",           // 31
};

typedef struct {
    PJitterBuffer pJitterBuffer;
    PBYTE pFrameBuffer;
    UINT32 frameBufferSize;
    UINT32 frameCount;
    UINT32 droppedCount;
    UINT32 firstRtpTimestamp;
    BOOL firstTimestampSet;
    UINT64 firstPcapTimestampUs;
    FILE* pOutputFile;
    UINT64 bytesWritten;
    BOOL summarize;
} AppContext, *PAppContext;

static const char* getNalTypeName(UINT8 nalType)
{
    if (nalType < ARRAY_SIZE(nalUnitTypeNames)) {
        return nalUnitTypeNames[nalType];
    }
    return "Unknown";
}

/* NAL summary: run-length encode consecutive same-type NAL units, e.g. "2xNON-IDR,SEI" */
#define MAX_NAL_RUNS     32
#define NAL_SUMMARY_SIZE 256

static VOID summarizeNalTypes(PBYTE pData, UINT32 size, char* pBuf, UINT32 bufSize)
{
    struct {
        UINT8 type;
        UINT32 count;
    } runs[MAX_NAL_RUNS];
    UINT32 numRuns = 0;
    UINT32 offset = 0;

    while (offset < size) {
        UINT32 scLen = 0;
        if (offset + 4 <= size && pData[offset] == 0 && pData[offset + 1] == 0 && pData[offset + 2] == 0 && pData[offset + 3] == 1) {
            scLen = 4;
        } else if (offset + 3 <= size && pData[offset] == 0 && pData[offset + 1] == 0 && pData[offset + 2] == 1) {
            scLen = 3;
        }

        if (scLen == 0) {
            offset++;
            continue;
        }

        UINT32 nalStart = offset + scLen;
        if (nalStart >= size) {
            break;
        }

        UINT8 nalType = pData[nalStart] & 0x1F;
        if (numRuns > 0 && runs[numRuns - 1].type == nalType) {
            runs[numRuns - 1].count++;
        } else if (numRuns < MAX_NAL_RUNS) {
            runs[numRuns].type = nalType;
            runs[numRuns].count = 1;
            numRuns++;
        }

        UINT32 nalEnd = size;
        for (UINT32 i = nalStart + 1; i + 2 < size; i++) {
            if (pData[i] == 0 && pData[i + 1] == 0 && (pData[i + 2] == 1 || (i + 3 < size && pData[i + 2] == 0 && pData[i + 3] == 1))) {
                nalEnd = i;
                break;
            }
        }
        offset = nalEnd;
    }

    UINT32 pos = 0;
    for (UINT32 i = 0; i < numRuns && pos < bufSize - 1; i++) {
        if (i > 0 && pos < bufSize - 2) {
            pBuf[pos++] = ',';
        }
        if (runs[i].count > 1) {
            INT32 w = snprintf(pBuf + pos, bufSize - pos, "%ux", runs[i].count);
            if (w > 0) {
                pos += (UINT32) w;
            }
        }
        INT32 w = snprintf(pBuf + pos, bufSize - pos, "%s", getNalTypeName(runs[i].type));
        if (w > 0) {
            pos += (UINT32) w;
        }
    }
    if (numRuns == 0) {
        snprintf(pBuf, bufSize, "(none)");
    } else {
        pBuf[pos] = '\0';
    }
}

static VOID printFrameSummaryLine(PBYTE pData, UINT32 size, UINT32 rtpTimestamp, UINT64 pcapReceiveTimeUs, UINT64 firstPcapTimestampUs,
                                  UINT32 frameIndex, UINT16 seqStart, UINT16 seqEnd)
{
    char nalSummary[NAL_SUMMARY_SIZE];
    summarizeNalTypes(pData, size, nalSummary, SIZEOF(nalSummary));
    DOUBLE pcapTimeSec = (DOUBLE)(pcapReceiveTimeUs - firstPcapTimestampUs) / 1000000.0;
    if (seqStart == seqEnd) {
        printf("frame=%u pcap=%.3fs rtp_ts=%u seq=%u size=%u nals=%s\n", frameIndex, pcapTimeSec, rtpTimestamp, seqStart, size, nalSummary);
    } else {
        printf("frame=%u pcap=%.3fs rtp_ts=%u seq=[%u..%u] size=%u nals=%s\n", frameIndex, pcapTimeSec, rtpTimestamp, seqStart, seqEnd, size,
               nalSummary);
    }
}

static VOID printFrameNalUnits(PBYTE pData, UINT32 size, UINT32 rtpTimestamp, UINT32 firstRtpTimestamp, UINT32 frameIndex, UINT16 seqStart,
                               UINT16 seqEnd)
{
    UINT32 offset = 0;
    DOUBLE timeSec = (DOUBLE) (rtpTimestamp - firstRtpTimestamp) / VIDEO_CLOCK_RATE;

    while (offset < size) {
        // Find start code (00 00 00 01 or 00 00 01)
        UINT32 scLen = 0;
        if (offset + 4 <= size && pData[offset] == 0 && pData[offset + 1] == 0 && pData[offset + 2] == 0 && pData[offset + 3] == 1) {
            scLen = 4;
        } else if (offset + 3 <= size && pData[offset] == 0 && pData[offset + 1] == 0 && pData[offset + 2] == 1) {
            scLen = 3;
        }

        if (scLen == 0) {
            offset++;
            continue;
        }

        UINT32 nalStart = offset + scLen;
        if (nalStart >= size) {
            break;
        }

        // Find next start code to determine NAL size
        UINT32 nalEnd = size;
        for (UINT32 i = nalStart + 1; i + 2 < size; i++) {
            if (pData[i] == 0 && pData[i + 1] == 0 && (pData[i + 2] == 1 || (i + 3 < size && pData[i + 2] == 0 && pData[i + 3] == 1))) {
                nalEnd = i;
                break;
            }
        }

        UINT8 nalType = pData[nalStart] & 0x1F;
        UINT32 nalSize = nalEnd - nalStart;

        if (seqStart == seqEnd) {
            printf("frame=%u time=%.3fs rtp_ts=%u seq=%u nal_type=%u (%s) size=%u\n", frameIndex, timeSec, rtpTimestamp, seqStart, nalType,
                   getNalTypeName(nalType), nalSize);
        } else {
            printf("frame=%u time=%.3fs rtp_ts=%u seq=[%u..%u] nal_type=%u (%s) size=%u\n", frameIndex, timeSec, rtpTimestamp, seqStart, seqEnd,
                   nalType, getNalTypeName(nalType), nalSize);
        }

        offset = nalEnd;
    }
}

static STATUS onFrameReady(UINT64 customData, UINT16 startIndex, UINT16 endIndex, UINT32 frameSize)
{
    STATUS retStatus = STATUS_SUCCESS;
    PAppContext pCtx = (PAppContext) customData;
    PRtpPacket pPacket = NULL;
    UINT32 filledSize = 0;

    CHK(pCtx != NULL, STATUS_NULL_ARG);

    if (frameSize > pCtx->frameBufferSize) {
        MEMFREE(pCtx->pFrameBuffer);
        pCtx->frameBufferSize = frameSize + 4096;
        pCtx->pFrameBuffer = (PBYTE) MEMALLOC(pCtx->frameBufferSize);
        CHK(pCtx->pFrameBuffer != NULL, STATUS_NOT_ENOUGH_MEMORY);
    }

    retStatus = jitterBufferGetPacket(pCtx->pJitterBuffer, startIndex, &pPacket);
    if (retStatus == STATUS_HASH_KEY_NOT_PRESENT) {
        retStatus = STATUS_SUCCESS;
    }
    CHK_STATUS(retStatus);
    CHK(pPacket != NULL, STATUS_NULL_ARG);

    if (!pCtx->firstTimestampSet) {
        pCtx->firstRtpTimestamp = pPacket->header.timestamp;
        pCtx->firstTimestampSet = TRUE;
    }

    CHK_STATUS(jitterBufferFillFrameData(pCtx->pJitterBuffer, pCtx->pFrameBuffer, frameSize, &filledSize, startIndex, endIndex));

    if (pCtx->pOutputFile != NULL && filledSize > 0) {
        fwrite(pCtx->pFrameBuffer, 1, filledSize, pCtx->pOutputFile);
        pCtx->bytesWritten += filledSize;
    }

    if (pCtx->summarize) {
        UINT64 pcapUs = pPacket->receivedTime / 10;
        printFrameSummaryLine(pCtx->pFrameBuffer, filledSize, pPacket->header.timestamp, pcapUs, pCtx->firstPcapTimestampUs, pCtx->frameCount,
                              startIndex, endIndex);
    } else {
        printFrameNalUnits(pCtx->pFrameBuffer, filledSize, pPacket->header.timestamp, pCtx->firstRtpTimestamp, pCtx->frameCount, startIndex,
                           endIndex);
    }
    pCtx->frameCount++;

CleanUp:
    return retStatus;
}

static STATUS onFrameDropped(UINT64 customData, UINT16 startIndex, UINT16 endIndex, UINT32 timestamp)
{
    STATUS retStatus = STATUS_SUCCESS;
    PAppContext pCtx = (PAppContext) customData;
    UINT32 partialSize = 0;
    UINT32 filledSize = 0;

    CHK(pCtx != NULL, STATUS_NULL_ARG);

    DOUBLE timeSec = 0;
    if (pCtx->firstTimestampSet) {
        timeSec = (DOUBLE) (timestamp - pCtx->firstRtpTimestamp) / VIDEO_CLOCK_RATE;
    }

    if (startIndex == endIndex) {
        printf("DROPPED frame at rtp_ts=%u time=%.3fs seq=%u\n", timestamp, timeSec, startIndex);
    } else {
        printf("DROPPED frame at rtp_ts=%u time=%.3fs seq=[%u..%u]\n", timestamp, timeSec, startIndex, endIndex);
    }
    pCtx->droppedCount++;

    // Simulate transceiverOnPartialFrame: extract whatever packets are available
    jitterBufferFillPartialFrameData(pCtx->pJitterBuffer, NULL, 0, &partialSize, startIndex, endIndex);
    CHK(partialSize > 0, retStatus);

    if (partialSize > pCtx->frameBufferSize) {
        MEMFREE(pCtx->pFrameBuffer);
        pCtx->frameBufferSize = partialSize + 4096;
        pCtx->pFrameBuffer = (PBYTE) MEMALLOC(pCtx->frameBufferSize);
        CHK(pCtx->pFrameBuffer != NULL, STATUS_NOT_ENOUGH_MEMORY);
    }

    jitterBufferFillPartialFrameData(pCtx->pJitterBuffer, pCtx->pFrameBuffer, partialSize, &filledSize, startIndex, endIndex);

    if (filledSize > 0) {
        if (pCtx->pOutputFile != NULL) {
            fwrite(pCtx->pFrameBuffer, 1, filledSize, pCtx->pOutputFile);
            pCtx->bytesWritten += filledSize;
        }
        printf("PARTIAL frame=%u time=%.3fs rtp_ts=%u seq=[%u..%u] size=%u\n", pCtx->frameCount, timeSec, timestamp, startIndex, endIndex,
               filledSize);
        printFrameNalUnits(pCtx->pFrameBuffer, filledSize, timestamp, pCtx->firstRtpTimestamp, pCtx->frameCount, startIndex, endIndex);
        pCtx->frameCount++;
    }

CleanUp:
    return retStatus;
}

INT32 main(INT32 argc, CHAR* argv[])
{
    STATUS retStatus = STATUS_SUCCESS;
    FILE* fp = NULL;
    BYTE globalHeader[PCAP_GLOBAL_HEADER_SIZE];
    BYTE recordHeader[PCAP_RECORD_HEADER_SIZE];
    PBYTE pPacketBuf = NULL;
    UINT32 packetBufSize = 0;
    AppContext ctx;
    UINT32 maxLatencyMs = 32;
    UINT32 totalPackets = 0;
    UINT32 rtpPackets = 0;
    UINT32 pliCount = 0;
    BOOL verbose = FALSE;
    const char* outputPath = NULL;

    MEMSET(&ctx, 0, SIZEOF(ctx));

    // Parse arguments: optional -v / -o flags, then pcap file, then optional max-latency-ms
    INT32 argIdx = 1;
    if (argIdx < argc && strcmp(argv[argIdx], "-v") == 0) {
        verbose = TRUE;
        argIdx++;
    }

    if (argIdx + 1 < argc && strcmp(argv[argIdx], "-o") == 0) {
        outputPath = argv[argIdx + 1];
        argIdx += 2;
    }

    if (argIdx < argc && strcmp(argv[argIdx], "-s") == 0) {
        ctx.summarize = TRUE;
        argIdx++;
    }

    if (argIdx >= argc) {
        printf("Usage: %s [-v] [-s] [-o <output.h264>] <pcap-file> [max-latency-ms]\n", argv[0]);
        printf("  -v             verbose: print each RTP packet as it is fed to the jitter buffer\n");
        printf("  -s             summary: print one line per frame (pcap time, rtp_ts, seq, size, NAL types)\n");
        printf("  -o <file>      write raw Annex-B H.264 stream to <file>\n");
        printf("  max-latency-ms defaults to 32\n");
        return 1;
    }

    if (argIdx + 1 < argc) {
        maxLatencyMs = (UINT32) STRTOUL(argv[argIdx + 1], NULL, 10);
        if (maxLatencyMs == 0) {
            maxLatencyMs = 32;
        }
    }

    initKvsWebRtc();

    if (verbose) {
        SET_LOGGER_LOG_LEVEL(LOG_LEVEL_DEBUG);
    }

    fp = fopen(argv[argIdx], "rb");
    if (fp == NULL) {
        printf("ERROR: Cannot open file %s\n", argv[argIdx]);
        retStatus = STATUS_OPEN_FILE_FAILED;
        goto CleanUp;
    }

    // Read and validate PCAP global header
    if (fread(globalHeader, 1, PCAP_GLOBAL_HEADER_SIZE, fp) != PCAP_GLOBAL_HEADER_SIZE) {
        printf("ERROR: Failed to read PCAP global header\n");
        retStatus = STATUS_INVALID_ARG;
        goto CleanUp;
    }

    // Check magic number (little-endian 0xA1B2C3D4)
    if (globalHeader[0] != 0xD4 || globalHeader[1] != 0xC3 || globalHeader[2] != 0xB2 || globalHeader[3] != 0xA1) {
        printf("ERROR: Not a valid PCAP file (bad magic)\n");
        retStatus = STATUS_INVALID_ARG;
        goto CleanUp;
    }

    if (outputPath != NULL) {
        ctx.pOutputFile = fopen(outputPath, "wb");
        if (ctx.pOutputFile == NULL) {
            printf("ERROR: Cannot open output file %s\n", outputPath);
            retStatus = STATUS_OPEN_FILE_FAILED;
            goto CleanUp;
        }
        printf("Writing H.264 output to %s\n", outputPath);
    }

    UINT64 maxLatency100ns = (UINT64) maxLatencyMs * HUNDREDS_OF_NANOS_IN_A_MILLISECOND;
    printf("Creating real-time jitter buffer with max latency %u ms\n", maxLatencyMs);

    ctx.frameBufferSize = MAX_FRAME_SIZE;
    ctx.pFrameBuffer = (PBYTE) MEMALLOC(ctx.frameBufferSize);
    CHK(ctx.pFrameBuffer != NULL, STATUS_NOT_ENOUGH_MEMORY);

    CHK_STATUS(createRealTimeJitterBuffer(onFrameReady, onFrameDropped, depayH264FromRtpPayload, maxLatency100ns, VIDEO_CLOCK_RATE, (UINT64) &ctx,
                                          FALSE, &ctx.pJitterBuffer));

    // Track first pcap timestamp for relative time display
    UINT64 firstPcapTimestampUs = 0;
    BOOL firstPcapTimestamp = TRUE;

    // Read packets
    while (fread(recordHeader, 1, PCAP_RECORD_HEADER_SIZE, fp) == PCAP_RECORD_HEADER_SIZE) {
        // Parse pcap record timestamp (seconds + microseconds, little-endian)
        UINT32 tsSec =
            (UINT32) recordHeader[0] | ((UINT32) recordHeader[1] << 8) | ((UINT32) recordHeader[2] << 16) | ((UINT32) recordHeader[3] << 24);
        UINT32 tsUsec =
            (UINT32) recordHeader[4] | ((UINT32) recordHeader[5] << 8) | ((UINT32) recordHeader[6] << 16) | ((UINT32) recordHeader[7] << 24);
        UINT64 pcapTimestampUs = (UINT64) tsSec * 1000000 + tsUsec;

        // Parse included length (little-endian)
        UINT32 inclLen =
            (UINT32) recordHeader[8] | ((UINT32) recordHeader[9] << 8) | ((UINT32) recordHeader[10] << 16) | ((UINT32) recordHeader[11] << 24);

        if (inclLen > 65535 + PCAP_TRANSPORT_HDR_SIZE) {
            printf("ERROR: Packet too large: %u\n", inclLen);
            break;
        }

        // Ensure buffer is large enough
        if (inclLen > packetBufSize) {
            SAFE_MEMFREE(pPacketBuf);
            packetBufSize = inclLen + 1024;
            pPacketBuf = (PBYTE) MEMALLOC(packetBufSize);
            CHK(pPacketBuf != NULL, STATUS_NOT_ENOUGH_MEMORY);
        }

        if (fread(pPacketBuf, 1, inclLen, fp) != inclLen) {
            break;
        }

        totalPackets++;

        // Check if it's a UDP packet (IP protocol = 0x11)
        if (inclLen < PCAP_TRANSPORT_HDR_SIZE) {
            continue;
        }

        PBYTE ipHeader = pPacketBuf + PCAP_ETHERNET_HDR_SIZE;
        UINT8 ipProtocol = ipHeader[9];
        if (ipProtocol != 0x11) {
            continue; // not UDP
        }

        PBYTE udpHeader = ipHeader + PCAP_IPV4_HDR_SIZE;
        UINT16 srcPort = ((UINT16) udpHeader[0] << 8) | udpHeader[1];
        UINT16 dstPort = ((UINT16) udpHeader[2] << 8) | udpHeader[3];

        // Determine direction from IP: 10.0.0.1 (0x0100000A LE) = local, 10.0.0.2 = remote
        UINT32 srcIp;
        MEMCPY(&srcIp, ipHeader + 12, 4);
        const char* direction = (srcIp == 0x0100000AU) ? "SEND" : "RECV";

        // Check for RTCP on port 5005 — look for PLI
        if (srcPort == PCAP_FAKE_RTCP_PORT || dstPort == PCAP_FAKE_RTCP_PORT) {
            PBYTE rtcpData = pPacketBuf + PCAP_TRANSPORT_HDR_SIZE;
            UINT32 rtcpLen = inclLen - PCAP_TRANSPORT_HDR_SIZE;
            // Walk compound RTCP packets
            UINT32 rtcpOffset = 0;
            while (rtcpOffset + 4 <= rtcpLen) {
                UINT8 fmt = rtcpData[rtcpOffset] & 0x1F;
                UINT8 packetType = rtcpData[rtcpOffset + 1];
                UINT16 lengthWords = ((UINT16) rtcpData[rtcpOffset + 2] << 8) | rtcpData[rtcpOffset + 3];
                UINT32 packetBytes = ((UINT32) lengthWords + 1) * 4;
                // PSFB (206) with FMT=1 is PLI
                if (packetType == RTCP_PACKET_TYPE_PAYLOAD_SPECIFIC_FEEDBACK && fmt == RTCP_PSFB_PLI) {
                    DOUBLE timeSec = 0;
                    if (!firstPcapTimestamp) {
                        timeSec = (DOUBLE) (pcapTimestampUs - firstPcapTimestampUs) / 1000000.0;
                    }
                    printf("PLI %s time=%.3fs\n", direction, timeSec);
                    pliCount++;
                }
                rtcpOffset += packetBytes;
            }
            continue;
        }

        // Only process RTP packets (port 5004)
        if (dstPort != PCAP_FAKE_RTP_PORT) {
            continue;
        }

        PBYTE rtpData = pPacketBuf + PCAP_TRANSPORT_HDR_SIZE;
        UINT32 rtpLen = inclLen - PCAP_TRANSPORT_HDR_SIZE;

        if (rtpLen < 12) {
            continue; // too short for RTP header
        }

        // Check payload type
        UINT8 pt = rtpData[1] & 0x7F;
        if (pt != VIDEO_PT) {
            continue; // not our video stream
        }

        if (firstPcapTimestamp) {
            firstPcapTimestampUs = pcapTimestampUs;
            firstPcapTimestamp = FALSE;
            ctx.firstPcapTimestampUs = pcapTimestampUs;
        }

        // createRtpPacketFromBytes takes ownership of the buffer, so we must
        // allocate a copy (rtpData points into our reusable pPacketBuf).
        PBYTE pRtpCopy = (PBYTE) MEMALLOC(rtpLen);
        if (pRtpCopy == NULL) {
            printf("ERROR: Failed to allocate RTP copy buffer\n");
            retStatus = STATUS_NOT_ENOUGH_MEMORY;
            goto CleanUp;
        }
        MEMCPY(pRtpCopy, rtpData, rtpLen);

        PRtpPacket pRtpPacket = NULL;
        retStatus = createRtpPacketFromBytes(pRtpCopy, rtpLen, &pRtpPacket);
        if (STATUS_FAILED(retStatus)) {
            printf("WARNING: Failed to parse RTP packet, skipping\n");
            MEMFREE(pRtpCopy);
            retStatus = STATUS_SUCCESS;
            continue;
        }

        pRtpPacket->receivedTime = pcapTimestampUs * 10; // pcap µs → 100ns units

        if (verbose) {
            printf("rtp seq=%u rtp_ts=%u pcap_ts=%.6fs\n", pRtpPacket->header.sequenceNumber, pRtpPacket->header.timestamp,
                   (DOUBLE) pcapTimestampUs / 1000000.0);
        }

        BOOL discarded = FALSE;
        retStatus = jitterBufferPush(ctx.pJitterBuffer, pRtpPacket, &discarded);
        if (STATUS_FAILED(retStatus)) {
            printf("WARNING: jitterBufferPush failed: 0x%08x\n", retStatus);
            retStatus = STATUS_SUCCESS;
        }

        rtpPackets++;
    }

    // Flush remaining frames by destroying the jitter buffer
    printf("\n--- Flushing jitter buffer ---\n");
    freeJitterBuffer(&ctx.pJitterBuffer);
    ctx.pJitterBuffer = NULL;

    printf("\nSummary:\n");
    printf("  Total pcap packets: %u\n", totalPackets);
    printf("  H264 RTP packets:   %u\n", rtpPackets);
    printf("  Frames delivered:   %u\n", ctx.frameCount);
    printf("  Frames dropped:     %u\n", ctx.droppedCount);
    printf("  PLI packets:        %u\n", pliCount);
    if (ctx.pOutputFile != NULL) {
        printf("  H.264 bytes out:    %" PRIu64 "\n", ctx.bytesWritten);
    }

CleanUp:
    if (ctx.pJitterBuffer != NULL) {
        freeJitterBuffer(&ctx.pJitterBuffer);
    }
    SAFE_MEMFREE(ctx.pFrameBuffer);
    SAFE_MEMFREE(pPacketBuf);
    if (fp != NULL) {
        fclose(fp);
    }
    if (ctx.pOutputFile != NULL) {
        fclose(ctx.pOutputFile);
    }
    deinitKvsWebRtc();

    if (STATUS_FAILED(retStatus)) {
        printf("ERROR: 0x%08x\n", retStatus);
        return 1;
    }
    return 0;
}
