/**
 * pcapDump - Read a pcap file generated by PcapDump and print all packets
 * with detailed RTCP sub-packet parsing including TWCC feedback analysis.
 *
 * Usage: pcapDump <pcap-file>
 */

#include "../src/source/Include_i.h"

#define PCAP_GLOBAL_HEADER_SIZE 24
#define PCAP_RECORD_HEADER_SIZE 16
#define PCAP_ETHERNET_HDR_SIZE  14
#define PCAP_IPV4_HDR_SIZE      20
#define PCAP_UDP_HDR_SIZE       8
#define PCAP_TRANSPORT_HDR_SIZE (PCAP_ETHERNET_HDR_SIZE + PCAP_IPV4_HDR_SIZE + PCAP_UDP_HDR_SIZE)

static PBYTE findOneByteExtension(PBYTE pExtPayload, UINT32 extLength, UINT8 targetId, PUINT8 pDataLen)
{
    UINT32 offset = 0;
    while (offset < extLength) {
        UINT8 byte = pExtPayload[offset];
        if (byte == 0) {
            offset++;
            continue;
        }
        UINT8 id = (byte >> 4) & 0x0F;
        UINT8 len = (byte & 0x0F) + 1;
        if (id == 15) {
            break;
        }
        if (id == targetId) {
            if (pDataLen != NULL) {
                *pDataLen = len;
            }
            return pExtPayload + offset + 1;
        }
        offset += 1 + len;
    }
    return NULL;
}

static void dumpTwccFeedback(PBYTE pPayload, UINT32 payloadLen, PUINT32 pReceivedOut, PUINT32 pLostOut)
{
    if (pReceivedOut != NULL) {
        *pReceivedOut = 0;
    }
    if (pLostOut != NULL) {
        *pLostOut = 0;
    }
    if (payloadLen < 8) {
        return;
    }

    UINT16 baseSeqNum = getUnalignedInt16BigEndian(pPayload + 0);
    UINT16 packetStatusCount = getUnalignedInt16BigEndian(pPayload + 2);
    UINT32 referenceTimeRaw = ((UINT32) pPayload[4] << 16) | ((UINT32) pPayload[5] << 8) | pPayload[6];
    UINT8 fbPktCount = pPayload[7];

    printf("      base_seq=%u count=%u ref_time=%u (%.1fms) fb_pkt_count=%u\n", baseSeqNum, packetStatusCount, referenceTimeRaw,
           referenceTimeRaw * 64.0, fbPktCount);

    // Walk chunks to count received/lost
    UINT32 chunkOffset = 8;
    INT32 remaining = packetStatusCount;
    UINT32 received = 0, lost = 0;

    // First pass: find delta offset
    UINT32 tmpOffset = chunkOffset;
    INT32 tmpRemaining = remaining;
    while (tmpRemaining > 0 && tmpOffset + 2 <= payloadLen) {
        UINT16 chunk = getUnalignedInt16BigEndian(pPayload + tmpOffset);
        if (IS_TWCC_RUNLEN(chunk)) {
            tmpRemaining -= TWCC_RUNLEN_GET(chunk);
        } else {
            tmpRemaining -= MIN(TWCC_STATUSVECTOR_COUNT(chunk), tmpRemaining);
        }
        tmpOffset += 2;
    }
    UINT32 deltaOffset = tmpOffset;

    // Second pass: count and print
    UINT16 seq = baseSeqNum;
    DOUBLE arrivalMs = referenceTimeRaw * 64.0;
    UINT32 printLimit = 10;
    UINT32 printCount = 0;

    remaining = packetStatusCount;
    while (remaining > 0 && chunkOffset + 2 <= payloadLen) {
        UINT16 chunk = getUnalignedInt16BigEndian(pPayload + chunkOffset);

        if (IS_TWCC_RUNLEN(chunk)) {
            UINT8 status = TWCC_RUNLEN_STATUS_SYMBOL(chunk);
            UINT32 count = TWCC_RUNLEN_GET(chunk);
            UINT32 i;
            for (i = 0; i < count && remaining > 0; i++) {
                if (status == TWCC_STATUS_SYMBOL_NOTRECEIVED) {
                    lost++;
                    if (printCount < printLimit) {
                        printf("        seq=%u LOST\n", seq);
                        printCount++;
                    }
                } else {
                    received++;
                    INT16 delta = 0;
                    if (status == TWCC_STATUS_SYMBOL_SMALLDELTA && deltaOffset < payloadLen) {
                        delta = (INT16) pPayload[deltaOffset];
                        deltaOffset++;
                    } else if (status == TWCC_STATUS_SYMBOL_LARGEDELTA && deltaOffset + 1 < payloadLen) {
                        delta = getUnalignedInt16BigEndian(pPayload + deltaOffset);
                        deltaOffset += 2;
                    }
                    arrivalMs += delta * 0.25;
                    if (printCount < printLimit) {
                        printf("        seq=%u recv arr=%.2fms delta=%.2fms\n", seq, arrivalMs, delta * 0.25);
                        printCount++;
                    }
                }
                seq++;
                remaining--;
            }
        } else {
            UINT32 statuses = MIN(TWCC_STATUSVECTOR_COUNT(chunk), (UINT32) remaining);
            UINT32 i;
            for (i = 0; i < statuses; i++) {
                UINT8 status = TWCC_STATUSVECTOR_STATUS(chunk, i);
                if (status == TWCC_STATUS_SYMBOL_NOTRECEIVED) {
                    lost++;
                    if (printCount < printLimit) {
                        printf("        seq=%u LOST\n", seq);
                        printCount++;
                    }
                } else {
                    received++;
                    INT16 delta = 0;
                    if (status == TWCC_STATUS_SYMBOL_SMALLDELTA && deltaOffset < payloadLen) {
                        delta = (INT16) pPayload[deltaOffset];
                        deltaOffset++;
                    } else if (status == TWCC_STATUS_SYMBOL_LARGEDELTA && deltaOffset + 1 < payloadLen) {
                        delta = getUnalignedInt16BigEndian(pPayload + deltaOffset);
                        deltaOffset += 2;
                    }
                    arrivalMs += delta * 0.25;
                    if (printCount < printLimit) {
                        printf("        seq=%u recv arr=%.2fms delta=%.2fms\n", seq, arrivalMs, delta * 0.25);
                        printCount++;
                    }
                }
                seq++;
                remaining--;
            }
        }
        chunkOffset += 2;
    }

    if (printCount >= printLimit && (received + lost) > printLimit) {
        printf("        ... (%u more)\n", received + lost - printLimit);
    }
    printf("      summary: received=%u lost=%u total=%u loss=%.1f%%\n", received, lost, received + lost,
           (received + lost) > 0 ? lost * 100.0 / (received + lost) : 0.0);

    if (pReceivedOut != NULL) {
        *pReceivedOut = received;
    }
    if (pLostOut != NULL) {
        *pLostOut = lost;
    }
}

INT32 main(INT32 argc, CHAR* argv[])
{
    STATUS retStatus = STATUS_SUCCESS;
    FILE* fp = NULL;
    BYTE globalHeader[PCAP_GLOBAL_HEADER_SIZE];
    BYTE recordHeader[PCAP_RECORD_HEADER_SIZE];
    PBYTE pPacketBuf = NULL;
    UINT32 packetBufSize = 0;
    UINT32 totalPackets = 0;
    UINT32 rtpSend = 0, rtpRecv = 0, rtcpSend = 0, rtcpRecv = 0, sctpCount = 0;
    UINT32 twccRecvCount = 0, twccSendCount = 0;
    UINT64 totalTwccReceived = 0, totalTwccLost = 0;
    UINT64 totalTwccSendReceived = 0, totalTwccSendLost = 0;

    // RTT estimation: 2x one-way delay from SR NTP timestamp vs PCAP arrival time
    UINT32 rttSampleCount = 0;
    DOUBLE totalRttMs = 0.0, minRttMs = 1e9, maxRttMs = 0.0;

    // RR-based loss and jitter
    UINT32 rrSampleCount = 0;
    UINT32 lastCumLost = 0;
    DOUBLE totalFracLostPct = 0.0;
    DOUBLE totalJitterSumTs = 0.0;

    if (argc < 2) {
        printf("Usage: %s <pcap-file>\n", argv[0]);
        return 1;
    }

    initKvsWebRtc();

    fp = fopen(argv[1], "rb");
    if (fp == NULL) {
        printf("ERROR: Cannot open file %s\n", argv[1]);
        return 1;
    }

    if (fread(globalHeader, 1, PCAP_GLOBAL_HEADER_SIZE, fp) != PCAP_GLOBAL_HEADER_SIZE) {
        printf("ERROR: Failed to read PCAP global header\n");
        fclose(fp);
        return 1;
    }

    if (globalHeader[0] != 0xD4 || globalHeader[1] != 0xC3 || globalHeader[2] != 0xB2 || globalHeader[3] != 0xA1) {
        printf("ERROR: Not a valid PCAP file (bad magic)\n");
        fclose(fp);
        return 1;
    }

    UINT64 firstPcapTimestampUs = 0;
    BOOL firstPcapTimestamp = TRUE;

    while (fread(recordHeader, 1, PCAP_RECORD_HEADER_SIZE, fp) == PCAP_RECORD_HEADER_SIZE) {
        UINT32 tsSec =
            (UINT32) recordHeader[0] | ((UINT32) recordHeader[1] << 8) | ((UINT32) recordHeader[2] << 16) | ((UINT32) recordHeader[3] << 24);
        UINT32 tsUsec =
            (UINT32) recordHeader[4] | ((UINT32) recordHeader[5] << 8) | ((UINT32) recordHeader[6] << 16) | ((UINT32) recordHeader[7] << 24);
        UINT64 pcapTimestampUs = (UINT64) tsSec * 1000000 + tsUsec;

        UINT32 inclLen =
            (UINT32) recordHeader[8] | ((UINT32) recordHeader[9] << 8) | ((UINT32) recordHeader[10] << 16) | ((UINT32) recordHeader[11] << 24);

        if (inclLen > 65535 + PCAP_TRANSPORT_HDR_SIZE) {
            break;
        }

        if (inclLen > packetBufSize) {
            SAFE_MEMFREE(pPacketBuf);
            packetBufSize = inclLen + 1024;
            pPacketBuf = (PBYTE) MEMALLOC(packetBufSize);
            if (pPacketBuf == NULL) {
                break;
            }
        }

        if (fread(pPacketBuf, 1, inclLen, fp) != inclLen) {
            break;
        }

        totalPackets++;

        if (firstPcapTimestamp) {
            firstPcapTimestampUs = pcapTimestampUs;
            firstPcapTimestamp = FALSE;
        }
        DOUBLE timeSec = (DOUBLE) (pcapTimestampUs - firstPcapTimestampUs) / 1000000.0;

        if (inclLen < PCAP_TRANSPORT_HDR_SIZE) {
            continue;
        }

        PBYTE ipHeader = pPacketBuf + PCAP_ETHERNET_HDR_SIZE;
        UINT8 ipProtocol = ipHeader[9];

        // SCTP
        if (ipProtocol == 132) {
            sctpCount++;
            PBYTE sctpData = ipHeader + PCAP_IPV4_HDR_SIZE;
            UINT32 sctpLen = inclLen - PCAP_ETHERNET_HDR_SIZE - PCAP_IPV4_HDR_SIZE;
            if (sctpLen >= 12) {
                // SCTP common header: srcPort(2) + dstPort(2) + vtag(4) + checksum(4) = 12
                UINT16 sctpSrcPort = ((UINT16) sctpData[0] << 8) | sctpData[1];
                UINT16 sctpDstPort = ((UINT16) sctpData[2] << 8) | sctpData[3];
                UINT32 sctpVtag = getUnalignedInt32BigEndian(sctpData + 4);
                UINT32 srcIpSctp;
                MEMCPY(&srcIpSctp, ipHeader + 12, 4);
                BOOL isSctpSend = (srcIpSctp == 0x0100000AU);
                const char* sctpDir = isSctpSend ? "SEND" : "RECV";

                printf("%.3f %s SCTP %u bytes src=%u dst=%u vtag=0x%08x\n", timeSec, sctpDir, sctpLen, sctpSrcPort, sctpDstPort, sctpVtag);

                // Walk chunks
                UINT32 chkOff = 12;
                while (chkOff + 4 <= sctpLen) {
                    UINT8 chunkType = sctpData[chkOff];
                    UINT8 chunkFlags = sctpData[chkOff + 1];
                    UINT16 chunkLen = ((UINT16) sctpData[chkOff + 2] << 8) | sctpData[chkOff + 3];
                    if (chunkLen < 4 || chkOff + chunkLen > sctpLen) {
                        break;
                    }

                    switch (chunkType) {
                        case 0: { // DATA
                            if (chunkLen >= 16) {
                                UINT32 tsn = getUnalignedInt32BigEndian(sctpData + chkOff + 4);
                                UINT16 sid = ((UINT16) sctpData[chkOff + 8] << 8) | sctpData[chkOff + 9];
                                UINT16 ssn = ((UINT16) sctpData[chkOff + 10] << 8) | sctpData[chkOff + 11];
                                UINT32 ppid = getUnalignedInt32BigEndian(sctpData + chkOff + 12);
                                BOOL uBit = (chunkFlags & 0x04) != 0;
                                BOOL bBit = (chunkFlags & 0x02) != 0;
                                BOOL eBit = (chunkFlags & 0x01) != 0;
                                const char* ppidStr = "?";
                                if (ppid == 50)
                                    ppidStr = "DCEP";
                                else if (ppid == 51)
                                    ppidStr = "STRING";
                                else if (ppid == 53)
                                    ppidStr = "BINARY";
                                else if (ppid == 56)
                                    ppidStr = "STRING_EMPTY";
                                else if (ppid == 57)
                                    ppidStr = "BINARY_EMPTY";
                                printf("  DATA tsn=%u sid=%u ssn=%u ppid=%u(%s) flags=[%s%s%s] payload=%u\n", tsn, sid, ssn, ppid, ppidStr,
                                       uBit ? "U" : "", bBit ? "B" : "", eBit ? "E" : "", chunkLen - 16);
                                if (ppid == 50 && chunkLen > 16 + 2) { // DCEP
                                    PBYTE dcep = sctpData + chkOff + 16;
                                    UINT32 dcepLen = chunkLen - 16;
                                    printf("    DCEP msgType=0x%02x channelType=0x%02x", dcep[0], dcep[1]);
                                    if (dcepLen >= 12) {
                                        UINT16 prio = ((UINT16) dcep[2] << 8) | dcep[3];
                                        UINT32 reliParam = getUnalignedInt32BigEndian(dcep + 4);
                                        UINT16 labelLen = ((UINT16) dcep[8] << 8) | dcep[9];
                                        UINT16 protoLen = ((UINT16) dcep[10] << 8) | dcep[11];
                                        printf(" prio=%u reliParam=%u labelLen=%u protoLen=%u", prio, reliParam, labelLen, protoLen);
                                        if (dcepLen >= 12u + labelLen) {
                                            printf(" label=\"%.*s\"", labelLen, dcep + 12);
                                        }
                                    }
                                    printf("\n");
                                }
                            }
                            break;
                        }
                        case 1:
                            printf("  INIT\n");
                            break;
                        case 2:
                            printf("  INIT-ACK\n");
                            break;
                        case 3: { // SACK
                            if (chunkLen >= 16) {
                                UINT32 cumTsn = getUnalignedInt32BigEndian(sctpData + chkOff + 4);
                                UINT32 arwnd = getUnalignedInt32BigEndian(sctpData + chkOff + 8);
                                UINT16 nGaps = ((UINT16) sctpData[chkOff + 12] << 8) | sctpData[chkOff + 13];
                                UINT16 nDups = ((UINT16) sctpData[chkOff + 14] << 8) | sctpData[chkOff + 15];
                                printf("  SACK cumTsn=%u arwnd=%u gaps=%u dups=%u\n", cumTsn, arwnd, nGaps, nDups);
                            }
                            break;
                        }
                        case 6:
                            printf("  ABORT\n");
                            break;
                        case 7:
                            printf("  SHUTDOWN\n");
                            break;
                        case 10:
                            printf("  COOKIE-ECHO\n");
                            break;
                        case 11:
                            printf("  COOKIE-ACK\n");
                            break;
                        case 192: { // FORWARD-TSN
                            if (chunkLen >= 8) {
                                UINT32 newCumTsn = getUnalignedInt32BigEndian(sctpData + chkOff + 4);
                                printf("  FORWARD-TSN newCumTsn=%u\n", newCumTsn);
                            }
                            break;
                        }
                        default:
                            printf("  CHUNK type=%u flags=0x%02x len=%u\n", chunkType, chunkFlags, chunkLen);
                            break;
                    }
                    // Advance to next chunk (padded to 4 bytes)
                    chkOff += ((chunkLen + 3) & ~3u);
                }
            }
            continue;
        }

        if (ipProtocol != 0x11) {
            continue;
        }

        PBYTE udpHeader = ipHeader + PCAP_IPV4_HDR_SIZE;
        UINT16 srcPort = ((UINT16) udpHeader[0] << 8) | udpHeader[1];
        UINT16 dstPort = ((UINT16) udpHeader[2] << 8) | udpHeader[3];

        UINT32 srcIp;
        MEMCPY(&srcIp, ipHeader + 12, 4);
        BOOL isSend = (srcIp == 0x0100000AU);
        const char* direction = isSend ? "SEND" : "RECV";

        PBYTE payload = pPacketBuf + PCAP_TRANSPORT_HDR_SIZE;
        UINT32 payloadLen = inclLen - PCAP_TRANSPORT_HDR_SIZE;

        // RTP
        if (srcPort == PCAP_FAKE_RTP_PORT || dstPort == PCAP_FAKE_RTP_PORT) {
            if (isSend) {
                rtpSend++;
            } else {
                rtpRecv++;
            }

            if (payloadLen >= 12) {
                UINT8 version = (payload[0] >> 6) & 3;
                UINT8 extension = (payload[0] >> 4) & 1;
                UINT8 cc = payload[0] & 0xF;
                UINT8 pt = payload[1] & 0x7F;
                UINT16 seq = getUnalignedInt16BigEndian(payload + 2);
                UINT32 timestamp = getUnalignedInt32BigEndian(payload + 4);
                UINT32 ssrc = getUnalignedInt32BigEndian(payload + 8);

                printf("%.3f %s RTP pt=%u seq=%u ts=%u ssrc=0x%08x size=%u", timeSec, direction, pt, seq, timestamp, ssrc, payloadLen);

                if (extension) {
                    UINT32 csrcOffset = 12 + cc * 4;
                    if (payloadLen > csrcOffset + 4) {
                        UINT16 extProfile = getUnalignedInt16BigEndian(payload + csrcOffset);
                        UINT16 extLen = getUnalignedInt16BigEndian(payload + csrcOffset + 2);
                        printf(" ext=0x%04X(%u)", extProfile, extLen);

                        if (extProfile == TWCC_EXT_PROFILE) {
                            PBYTE extPayload = payload + csrcOffset + 4;
                            UINT32 extBytes = extLen * 4;
                            // Try common TWCC ext IDs
                            UINT8 extId;
                            for (extId = 1; extId <= 14; extId++) {
                                PBYTE extData = findOneByteExtension(extPayload, extBytes, extId, NULL);
                                if (extData != NULL) {
                                    UINT16 twccSeq = getUnalignedInt16BigEndian(extData);
                                    printf(" twcc_id=%u twcc_seq=%u", extId, twccSeq);
                                    break;
                                }
                            }
                        }
                    }
                }
                printf("\n");
            }
            continue;
        }

        // RTCP
        if (srcPort == PCAP_FAKE_RTCP_PORT || dstPort == PCAP_FAKE_RTCP_PORT) {
            if (isSend) {
                rtcpSend++;
            } else {
                rtcpRecv++;
            }

            printf("%.3f %s RTCP %u bytes\n", timeSec, direction, payloadLen);

            // Walk compound RTCP
            UINT32 rtcpOffset = 0;
            UINT32 subIdx = 0;
            while (rtcpOffset + 4 <= payloadLen) {
                UINT8 version = (payload[rtcpOffset] >> 6) & 3;
                UINT8 padding = (payload[rtcpOffset] >> 5) & 1;
                UINT8 fmt = payload[rtcpOffset] & 0x1F;
                UINT8 pt = payload[rtcpOffset + 1];
                UINT16 lengthWords = getUnalignedInt16BigEndian(payload + rtcpOffset + 2);
                UINT32 packetBytes = ((UINT32) lengthWords + 1) * 4;

                if (packetBytes > payloadLen - rtcpOffset) {
                    printf("  [%u] TRUNCATED: need %u bytes, have %u\n", subIdx, packetBytes, payloadLen - rtcpOffset);
                    break;
                }

                printf("  [%u] V=%u P=%u FMT=%u PT=%u len=%u (%u bytes)", subIdx, version, padding, fmt, pt, lengthWords, packetBytes);

                switch (pt) {
                    case 200:
                        printf(" (SR)");
                        break;
                    case 201:
                        printf(" (RR)");
                        break;
                    case 202:
                        printf(" (SDES)");
                        break;
                    case 203:
                        printf(" (BYE)");
                        break;
                    case 205:
                        printf(" (RTPFB fmt=%u)", fmt);
                        if (fmt == 1) {
                            printf(" NACK");
                        } else if (fmt == 15) {
                            printf(" TWCC");
                        }
                        break;
                    case 206:
                        printf(" (PSFB fmt=%u)", fmt);
                        if (fmt == 1) {
                            printf(" PLI");
                        } else if (fmt == 4) {
                            printf(" FIR");
                        } else if (fmt == 15) {
                            printf(" AFB/REMB");
                        }
                        break;
                    default:
                        break;
                }
                printf("\n");

                // SR: extract NTP timestamp and estimate RTT from PCAP arrival time
                if (pt == 200 && packetBytes >= 28) {
                    UINT32 ntpMSW = getUnalignedInt32BigEndian(payload + rtcpOffset + 8);
                    UINT32 ntpLSW = getUnalignedInt32BigEndian(payload + rtcpOffset + 12);
                    // NTP epoch is Jan 1 1900; Unix epoch is Jan 1 1970; diff = 2208988800s
                    INT64 ntpUnixSec = (INT64) ntpMSW - 2208988800LL;
                    DOUBLE ntpUnixTime = (DOUBLE) ntpUnixSec + (DOUBLE) ntpLSW / 4294967296.0;
                    DOUBLE pcapUnixTime = (DOUBLE) pcapTimestampUs / 1000000.0;
                    DOUBLE owdMs = (pcapUnixTime - ntpUnixTime) * 1000.0;
                    DOUBLE rttMs = owdMs * 2.0;
                    printf("    ntp_unix=%.3f pcap_unix=%.3f owd=%.1fms rtt_est=%.1fms\n", ntpUnixTime, pcapUnixTime, owdMs, rttMs);
                    if (rttMs > 0.0 && rttMs < 10000.0) {
                        totalRttMs += rttMs;
                        rttSampleCount++;
                        if (rttMs < minRttMs)
                            minRttMs = rttMs;
                        if (rttMs > maxRttMs)
                            maxRttMs = rttMs;
                    }
                }

                // RR: extract per-report-block loss, jitter, DLSR
                if (pt == 201 && packetBytes >= 32 && fmt >= 1) {
                    // report block 0 starts at rtcpOffset+8
                    UINT32 srcSsrc = getUnalignedInt32BigEndian(payload + rtcpOffset + 8);
                    UINT8 fracLost = payload[rtcpOffset + 12];
                    UINT32 cumLost = ((UINT32) payload[rtcpOffset + 13] << 16) | ((UINT32) payload[rtcpOffset + 14] << 8) | payload[rtcpOffset + 15];
                    UINT32 jitter = getUnalignedInt32BigEndian(payload + rtcpOffset + 20);
                    UINT32 lsr = getUnalignedInt32BigEndian(payload + rtcpOffset + 24);
                    UINT32 dlsr = getUnalignedInt32BigEndian(payload + rtcpOffset + 28);
                    DOUBLE dlsrMs = dlsr * 1000.0 / 65536.0;
                    DOUBLE fracLostPct = fracLost * 100.0 / 256.0;
                    printf("    source=0x%08x frac_lost=%u (%.1f%%) cum_lost=%u jitter=%uts dlsr=%.1fms\n", srcSsrc, fracLost, fracLostPct, cumLost,
                           jitter, dlsrMs);
                    rrSampleCount++;
                    totalFracLostPct += fracLostPct;
                    lastCumLost = cumLost;
                    totalJitterSumTs += jitter;
                }

                // Detailed TWCC parsing
                if (pt == 205 && fmt == 15 && packetBytes > 16) {
                    // TWCC payload starts after RTCP header (4 bytes) + sender SSRC (4 bytes) + media SSRC (4 bytes) = 12 bytes
                    UINT32 twccPayloadOffset = rtcpOffset + 12;
                    UINT32 twccPayloadLen = packetBytes - 12;
                    if (twccPayloadOffset + 8 <= payloadLen) {
                        UINT32 fbReceived = 0, fbLost = 0;
                        dumpTwccFeedback(payload + twccPayloadOffset, twccPayloadLen, &fbReceived, &fbLost);

                        if (!isSend) {
                            twccRecvCount++;
                            totalTwccReceived += fbReceived;
                            totalTwccLost += fbLost;
                        } else {
                            twccSendCount++;
                            totalTwccSendReceived += fbReceived;
                            totalTwccSendLost += fbLost;
                        }
                    }
                }

                rtcpOffset += packetBytes;
                subIdx++;
            }
            continue;
        }
    }

    printf("\n=== Summary ===\n");
    printf("Total pcap packets: %u\n", totalPackets);
    printf("RTP:  send=%u recv=%u\n", rtpSend, rtpRecv);
    printf("RTCP: send=%u recv=%u\n", rtcpSend, rtcpRecv);
    printf("SCTP: %u\n", sctpCount);
    printf("TWCC feedbacks recv'd (remote→us): %u  acked: %" PRIu64 " lost: %" PRIu64 " total: %" PRIu64 " loss: %.1f%%\n", twccRecvCount,
           totalTwccReceived, totalTwccLost, totalTwccReceived + totalTwccLost,
           (totalTwccReceived + totalTwccLost) > 0 ? totalTwccLost * 100.0 / (totalTwccReceived + totalTwccLost) : 0.0);
    printf("TWCC feedbacks sent  (us→remote): %u  acked: %" PRIu64 " lost: %" PRIu64 " total: %" PRIu64 " loss: %.1f%%\n", twccSendCount,
           totalTwccSendReceived, totalTwccSendLost, totalTwccSendReceived + totalTwccSendLost,
           (totalTwccSendReceived + totalTwccSendLost) > 0 ? totalTwccSendLost * 100.0 / (totalTwccSendReceived + totalTwccSendLost) : 0.0);
    printf("\n--- RTT (from SR NTP vs PCAP arrival, assumes NTP-synced clocks) ---\n");
    if (rttSampleCount > 0) {
        printf("Samples: %u  avg: %.1fms  min: %.1fms  max: %.1fms\n", rttSampleCount, totalRttMs / rttSampleCount, minRttMs, maxRttMs);
    } else {
        printf("No valid RTT samples\n");
    }
    printf("\n--- RR-based loss and jitter ---\n");
    if (rrSampleCount > 0) {
        printf("RR reports: %u  avg_frac_lost: %.1f%%  cumulative_lost: %u  avg_jitter: %.0f ts-units\n", rrSampleCount,
               totalFracLostPct / rrSampleCount, lastCumLost, totalJitterSumTs / rrSampleCount);
    } else {
        printf("No RR samples\n");
    }

    SAFE_MEMFREE(pPacketBuf);
    if (fp != NULL) {
        fclose(fp);
    }
    deinitKvsWebRtc();

    return 0;
}
