/**
 * pcapDump - Read a pcap file generated by PcapDump and print all packets
 * with detailed RTCP sub-packet parsing including TWCC feedback analysis.
 *
 * Usage: pcapDump <pcap-file>
 */

#include "../src/source/Include_i.h"

#define PCAP_GLOBAL_HEADER_SIZE 24
#define PCAP_RECORD_HEADER_SIZE 16
#define PCAP_ETHERNET_HDR_SIZE  14
#define PCAP_IPV4_HDR_SIZE      20
#define PCAP_UDP_HDR_SIZE       8
#define PCAP_TRANSPORT_HDR_SIZE (PCAP_ETHERNET_HDR_SIZE + PCAP_IPV4_HDR_SIZE + PCAP_UDP_HDR_SIZE)

static PBYTE findOneByteExtension(PBYTE pExtPayload, UINT32 extLength, UINT8 targetId, PUINT8 pDataLen)
{
    UINT32 offset = 0;
    while (offset < extLength) {
        UINT8 byte = pExtPayload[offset];
        if (byte == 0) {
            offset++;
            continue;
        }
        UINT8 id = (byte >> 4) & 0x0F;
        UINT8 len = (byte & 0x0F) + 1;
        if (id == 15) {
            break;
        }
        if (id == targetId) {
            if (pDataLen != NULL) {
                *pDataLen = len;
            }
            return pExtPayload + offset + 1;
        }
        offset += 1 + len;
    }
    return NULL;
}

static void dumpTwccFeedback(PBYTE pPayload, UINT32 payloadLen, PUINT32 pReceivedOut, PUINT32 pLostOut)
{
    if (pReceivedOut != NULL) {
        *pReceivedOut = 0;
    }
    if (pLostOut != NULL) {
        *pLostOut = 0;
    }
    if (payloadLen < 8) {
        return;
    }

    UINT16 baseSeqNum = getUnalignedInt16BigEndian(pPayload + 0);
    UINT16 packetStatusCount = getUnalignedInt16BigEndian(pPayload + 2);
    UINT32 referenceTimeRaw = ((UINT32) pPayload[4] << 16) | ((UINT32) pPayload[5] << 8) | pPayload[6];
    UINT8 fbPktCount = pPayload[7];

    printf("      base_seq=%u count=%u ref_time=%u (%.1fms) fb_pkt_count=%u\n", baseSeqNum, packetStatusCount, referenceTimeRaw,
           referenceTimeRaw * 64.0, fbPktCount);

    // Walk chunks to count received/lost
    UINT32 chunkOffset = 8;
    INT32 remaining = packetStatusCount;
    UINT32 received = 0, lost = 0;

    // First pass: find delta offset
    UINT32 tmpOffset = chunkOffset;
    INT32 tmpRemaining = remaining;
    while (tmpRemaining > 0 && tmpOffset + 2 <= payloadLen) {
        UINT16 chunk = getUnalignedInt16BigEndian(pPayload + tmpOffset);
        if (IS_TWCC_RUNLEN(chunk)) {
            tmpRemaining -= TWCC_RUNLEN_GET(chunk);
        } else {
            tmpRemaining -= MIN(TWCC_STATUSVECTOR_COUNT(chunk), tmpRemaining);
        }
        tmpOffset += 2;
    }
    UINT32 deltaOffset = tmpOffset;

    // Second pass: count and print
    UINT16 seq = baseSeqNum;
    DOUBLE arrivalMs = referenceTimeRaw * 64.0;
    UINT32 printLimit = 10;
    UINT32 printCount = 0;

    remaining = packetStatusCount;
    while (remaining > 0 && chunkOffset + 2 <= payloadLen) {
        UINT16 chunk = getUnalignedInt16BigEndian(pPayload + chunkOffset);

        if (IS_TWCC_RUNLEN(chunk)) {
            UINT8 status = TWCC_RUNLEN_STATUS_SYMBOL(chunk);
            UINT32 count = TWCC_RUNLEN_GET(chunk);
            UINT32 i;
            for (i = 0; i < count && remaining > 0; i++) {
                if (status == TWCC_STATUS_SYMBOL_NOTRECEIVED) {
                    lost++;
                    if (printCount < printLimit) {
                        printf("        seq=%u LOST\n", seq);
                        printCount++;
                    }
                } else {
                    received++;
                    INT16 delta = 0;
                    if (status == TWCC_STATUS_SYMBOL_SMALLDELTA && deltaOffset < payloadLen) {
                        delta = (INT16) pPayload[deltaOffset];
                        deltaOffset++;
                    } else if (status == TWCC_STATUS_SYMBOL_LARGEDELTA && deltaOffset + 1 < payloadLen) {
                        delta = getUnalignedInt16BigEndian(pPayload + deltaOffset);
                        deltaOffset += 2;
                    }
                    arrivalMs += delta * 0.25;
                    if (printCount < printLimit) {
                        printf("        seq=%u recv arr=%.2fms delta=%.2fms\n", seq, arrivalMs, delta * 0.25);
                        printCount++;
                    }
                }
                seq++;
                remaining--;
            }
        } else {
            UINT32 statuses = MIN(TWCC_STATUSVECTOR_COUNT(chunk), (UINT32) remaining);
            UINT32 i;
            for (i = 0; i < statuses; i++) {
                UINT8 status = TWCC_STATUSVECTOR_STATUS(chunk, i);
                if (status == TWCC_STATUS_SYMBOL_NOTRECEIVED) {
                    lost++;
                    if (printCount < printLimit) {
                        printf("        seq=%u LOST\n", seq);
                        printCount++;
                    }
                } else {
                    received++;
                    INT16 delta = 0;
                    if (status == TWCC_STATUS_SYMBOL_SMALLDELTA && deltaOffset < payloadLen) {
                        delta = (INT16) pPayload[deltaOffset];
                        deltaOffset++;
                    } else if (status == TWCC_STATUS_SYMBOL_LARGEDELTA && deltaOffset + 1 < payloadLen) {
                        delta = getUnalignedInt16BigEndian(pPayload + deltaOffset);
                        deltaOffset += 2;
                    }
                    arrivalMs += delta * 0.25;
                    if (printCount < printLimit) {
                        printf("        seq=%u recv arr=%.2fms delta=%.2fms\n", seq, arrivalMs, delta * 0.25);
                        printCount++;
                    }
                }
                seq++;
                remaining--;
            }
        }
        chunkOffset += 2;
    }

    if (printCount >= printLimit && (received + lost) > printLimit) {
        printf("        ... (%u more)\n", received + lost - printLimit);
    }
    printf("      summary: received=%u lost=%u total=%u loss=%.1f%%\n", received, lost, received + lost,
           (received + lost) > 0 ? lost * 100.0 / (received + lost) : 0.0);

    if (pReceivedOut != NULL) {
        *pReceivedOut = received;
    }
    if (pLostOut != NULL) {
        *pLostOut = lost;
    }
}

INT32 main(INT32 argc, CHAR* argv[])
{
    STATUS retStatus = STATUS_SUCCESS;
    FILE* fp = NULL;
    BYTE globalHeader[PCAP_GLOBAL_HEADER_SIZE];
    BYTE recordHeader[PCAP_RECORD_HEADER_SIZE];
    PBYTE pPacketBuf = NULL;
    UINT32 packetBufSize = 0;
    UINT32 totalPackets = 0;
    UINT32 rtpSend = 0, rtpRecv = 0, rtcpSend = 0, rtcpRecv = 0, sctpCount = 0;
    UINT32 twccRecvCount = 0;
    UINT64 totalTwccReceived = 0, totalTwccLost = 0;

    if (argc < 2) {
        printf("Usage: %s <pcap-file>\n", argv[0]);
        return 1;
    }

    initKvsWebRtc();

    fp = fopen(argv[1], "rb");
    if (fp == NULL) {
        printf("ERROR: Cannot open file %s\n", argv[1]);
        return 1;
    }

    if (fread(globalHeader, 1, PCAP_GLOBAL_HEADER_SIZE, fp) != PCAP_GLOBAL_HEADER_SIZE) {
        printf("ERROR: Failed to read PCAP global header\n");
        fclose(fp);
        return 1;
    }

    if (globalHeader[0] != 0xD4 || globalHeader[1] != 0xC3 || globalHeader[2] != 0xB2 || globalHeader[3] != 0xA1) {
        printf("ERROR: Not a valid PCAP file (bad magic)\n");
        fclose(fp);
        return 1;
    }

    UINT64 firstPcapTimestampUs = 0;
    BOOL firstPcapTimestamp = TRUE;

    while (fread(recordHeader, 1, PCAP_RECORD_HEADER_SIZE, fp) == PCAP_RECORD_HEADER_SIZE) {
        UINT32 tsSec =
            (UINT32) recordHeader[0] | ((UINT32) recordHeader[1] << 8) | ((UINT32) recordHeader[2] << 16) | ((UINT32) recordHeader[3] << 24);
        UINT32 tsUsec =
            (UINT32) recordHeader[4] | ((UINT32) recordHeader[5] << 8) | ((UINT32) recordHeader[6] << 16) | ((UINT32) recordHeader[7] << 24);
        UINT64 pcapTimestampUs = (UINT64) tsSec * 1000000 + tsUsec;

        UINT32 inclLen =
            (UINT32) recordHeader[8] | ((UINT32) recordHeader[9] << 8) | ((UINT32) recordHeader[10] << 16) | ((UINT32) recordHeader[11] << 24);

        if (inclLen > 65535 + PCAP_TRANSPORT_HDR_SIZE) {
            break;
        }

        if (inclLen > packetBufSize) {
            SAFE_MEMFREE(pPacketBuf);
            packetBufSize = inclLen + 1024;
            pPacketBuf = (PBYTE) MEMALLOC(packetBufSize);
            if (pPacketBuf == NULL) {
                break;
            }
        }

        if (fread(pPacketBuf, 1, inclLen, fp) != inclLen) {
            break;
        }

        totalPackets++;

        if (firstPcapTimestamp) {
            firstPcapTimestampUs = pcapTimestampUs;
            firstPcapTimestamp = FALSE;
        }
        DOUBLE timeSec = (DOUBLE) (pcapTimestampUs - firstPcapTimestampUs) / 1000000.0;

        if (inclLen < PCAP_TRANSPORT_HDR_SIZE) {
            continue;
        }

        PBYTE ipHeader = pPacketBuf + PCAP_ETHERNET_HDR_SIZE;
        UINT8 ipProtocol = ipHeader[9];

        // SCTP
        if (ipProtocol == 132) {
            sctpCount++;
            continue;
        }

        if (ipProtocol != 0x11) {
            continue;
        }

        PBYTE udpHeader = ipHeader + PCAP_IPV4_HDR_SIZE;
        UINT16 srcPort = ((UINT16) udpHeader[0] << 8) | udpHeader[1];
        UINT16 dstPort = ((UINT16) udpHeader[2] << 8) | udpHeader[3];

        UINT32 srcIp;
        MEMCPY(&srcIp, ipHeader + 12, 4);
        BOOL isSend = (srcIp == 0x0100000AU);
        const char* direction = isSend ? "SEND" : "RECV";

        PBYTE payload = pPacketBuf + PCAP_TRANSPORT_HDR_SIZE;
        UINT32 payloadLen = inclLen - PCAP_TRANSPORT_HDR_SIZE;

        // RTP
        if (srcPort == PCAP_FAKE_RTP_PORT || dstPort == PCAP_FAKE_RTP_PORT) {
            if (isSend) {
                rtpSend++;
            } else {
                rtpRecv++;
            }

            if (payloadLen >= 12) {
                UINT8 version = (payload[0] >> 6) & 3;
                UINT8 extension = (payload[0] >> 4) & 1;
                UINT8 cc = payload[0] & 0xF;
                UINT8 pt = payload[1] & 0x7F;
                UINT16 seq = getUnalignedInt16BigEndian(payload + 2);
                UINT32 timestamp = getUnalignedInt32BigEndian(payload + 4);
                UINT32 ssrc = getUnalignedInt32BigEndian(payload + 8);

                printf("%.3f %s RTP pt=%u seq=%u ts=%u ssrc=0x%08x size=%u", timeSec, direction, pt, seq, timestamp, ssrc, payloadLen);

                if (extension) {
                    UINT32 csrcOffset = 12 + cc * 4;
                    if (payloadLen > csrcOffset + 4) {
                        UINT16 extProfile = getUnalignedInt16BigEndian(payload + csrcOffset);
                        UINT16 extLen = getUnalignedInt16BigEndian(payload + csrcOffset + 2);
                        printf(" ext=0x%04X(%u)", extProfile, extLen);

                        if (extProfile == TWCC_EXT_PROFILE) {
                            PBYTE extPayload = payload + csrcOffset + 4;
                            UINT32 extBytes = extLen * 4;
                            // Try common TWCC ext IDs
                            UINT8 extId;
                            for (extId = 1; extId <= 14; extId++) {
                                PBYTE extData = findOneByteExtension(extPayload, extBytes, extId, NULL);
                                if (extData != NULL) {
                                    UINT16 twccSeq = getUnalignedInt16BigEndian(extData);
                                    printf(" twcc_id=%u twcc_seq=%u", extId, twccSeq);
                                    break;
                                }
                            }
                        }
                    }
                }
                printf("\n");
            }
            continue;
        }

        // RTCP
        if (srcPort == PCAP_FAKE_RTCP_PORT || dstPort == PCAP_FAKE_RTCP_PORT) {
            if (isSend) {
                rtcpSend++;
            } else {
                rtcpRecv++;
            }

            printf("%.3f %s RTCP %u bytes\n", timeSec, direction, payloadLen);

            // Walk compound RTCP
            UINT32 rtcpOffset = 0;
            UINT32 subIdx = 0;
            while (rtcpOffset + 4 <= payloadLen) {
                UINT8 version = (payload[rtcpOffset] >> 6) & 3;
                UINT8 padding = (payload[rtcpOffset] >> 5) & 1;
                UINT8 fmt = payload[rtcpOffset] & 0x1F;
                UINT8 pt = payload[rtcpOffset + 1];
                UINT16 lengthWords = getUnalignedInt16BigEndian(payload + rtcpOffset + 2);
                UINT32 packetBytes = ((UINT32) lengthWords + 1) * 4;

                if (packetBytes > payloadLen - rtcpOffset) {
                    printf("  [%u] TRUNCATED: need %u bytes, have %u\n", subIdx, packetBytes, payloadLen - rtcpOffset);
                    break;
                }

                printf("  [%u] V=%u P=%u FMT=%u PT=%u len=%u (%u bytes)", subIdx, version, padding, fmt, pt, lengthWords, packetBytes);

                switch (pt) {
                    case 200:
                        printf(" (SR)");
                        break;
                    case 201:
                        printf(" (RR)");
                        break;
                    case 202:
                        printf(" (SDES)");
                        break;
                    case 203:
                        printf(" (BYE)");
                        break;
                    case 205:
                        printf(" (RTPFB fmt=%u)", fmt);
                        if (fmt == 1) {
                            printf(" NACK");
                        } else if (fmt == 15) {
                            printf(" TWCC");
                        }
                        break;
                    case 206:
                        printf(" (PSFB fmt=%u)", fmt);
                        if (fmt == 1) {
                            printf(" PLI");
                        } else if (fmt == 4) {
                            printf(" FIR");
                        } else if (fmt == 15) {
                            printf(" AFB/REMB");
                        }
                        break;
                    default:
                        break;
                }
                printf("\n");

                // Detailed TWCC parsing
                if (pt == 205 && fmt == 15 && packetBytes > 16) {
                    // TWCC payload starts after RTCP header (4 bytes) + sender SSRC (4 bytes) + media SSRC (4 bytes) = 12 bytes
                    // But the RTCP header fields occupy: V|P|FMT(1) + PT(1) + length(2) + sender_ssrc(4) + media_ssrc(4) = 12 bytes
                    // TWCC-specific fields start at offset 12 within the RTCP packet
                    UINT32 twccPayloadOffset = rtcpOffset + 12;
                    UINT32 twccPayloadLen = packetBytes - 12;
                    if (twccPayloadOffset + 8 <= payloadLen) {
                        UINT32 fbReceived = 0, fbLost = 0;
                        dumpTwccFeedback(payload + twccPayloadOffset, twccPayloadLen, &fbReceived, &fbLost);

                        if (!isSend) {
                            twccRecvCount++;
                            totalTwccReceived += fbReceived;
                            totalTwccLost += fbLost;
                        }
                    }
                }

                rtcpOffset += packetBytes;
                subIdx++;
            }
            continue;
        }
    }

    printf("\n=== Summary ===\n");
    printf("Total pcap packets: %u\n", totalPackets);
    printf("RTP:  send=%u recv=%u\n", rtpSend, rtpRecv);
    printf("RTCP: send=%u recv=%u\n", rtcpSend, rtcpRecv);
    printf("SCTP: %u\n", sctpCount);
    printf("TWCC feedbacks received: %u\n", twccRecvCount);
    printf("TWCC packets acked: %" PRIu64 " lost: %" PRIu64 " total: %" PRIu64 " loss: %.1f%%\n", totalTwccReceived, totalTwccLost,
           totalTwccReceived + totalTwccLost,
           (totalTwccReceived + totalTwccLost) > 0 ? totalTwccLost * 100.0 / (totalTwccReceived + totalTwccLost) : 0.0);

    SAFE_MEMFREE(pPacketBuf);
    if (fp != NULL) {
        fclose(fp);
    }
    deinitKvsWebRtc();

    return 0;
}
