/**
 * pcapGcc - Read a pcap file generated by PcapDump, extract sent RTP packets
 * (with TWCC extensions) and received TWCC RTCP feedback, feed them through
 * the GCC congestion controller, and print detailed per-feedback diagnostics.
 *
 * Usage: pcapGcc <pcap-file> [min-kbps] [initial-kbps] [max-kbps] [twcc-ext-id]
 *   Defaults: 2107 / 4214 / 8429 / 5
 */

#include "../src/source/Include_i.h"
#include "../src/source/PeerConnection/Gcc_i.h"

#define PCAP_GLOBAL_HEADER_SIZE 24
#define PCAP_RECORD_HEADER_SIZE 16
#define PCAP_ETHERNET_HDR_SIZE  14
#define PCAP_IPV4_HDR_SIZE      20
#define PCAP_UDP_HDR_SIZE       8
#define PCAP_TRANSPORT_HDR_SIZE (PCAP_ETHERNET_HDR_SIZE + PCAP_IPV4_HDR_SIZE + PCAP_UDP_HDR_SIZE)

#define DEFAULT_MIN_KBPS     2107
#define DEFAULT_INITIAL_KBPS 4214
#define DEFAULT_MAX_KBPS     8429
#define DEFAULT_TWCC_EXT_ID  5

// Copied from Rtcp.c (it is static there)
static PBYTE findOneByteExtension(PBYTE pExtPayload, UINT32 extLength, UINT8 targetId, PUINT8 pDataLen)
{
    UINT32 offset = 0;
    UINT8 id, len;

    while (offset < extLength) {
        UINT8 byte = pExtPayload[offset];

        if (byte == 0) {
            offset++;
            continue;
        }

        id = (byte >> 4) & 0x0F;
        len = (byte & 0x0F) + 1;

        if (id == 15) {
            break;
        }

        if (id == targetId) {
            if (pDataLen != NULL) {
                *pDataLen = len;
            }
            return pExtPayload + offset + 1;
        }

        offset += 1 + len;
    }

    return NULL;
}

static STATUS freeHashEntryValue(UINT64 customData, PHashEntry pHashEntry)
{
    UNUSED_PARAM(customData);
    if (pHashEntry != NULL && pHashEntry->value != 0) {
        MEMFREE((PVOID) pHashEntry->value);
    }
    return STATUS_SUCCESS;
}

static const char* gccStateName(GccState state)
{
    switch (state) {
        case GCC_STATE_HOLD:
            return "HOLD";
        case GCC_STATE_INCREASE:
            return "INCREASE";
        case GCC_STATE_DECREASE:
            return "DECREASE";
        default:
            return "UNKNOWN";
    }
}

INT32 main(INT32 argc, CHAR* argv[])
{
    STATUS retStatus = STATUS_SUCCESS;
    FILE* fp = NULL;
    BYTE globalHeader[PCAP_GLOBAL_HEADER_SIZE];
    BYTE recordHeader[PCAP_RECORD_HEADER_SIZE];
    PBYTE pPacketBuf = NULL;
    UINT32 packetBufSize = 0;
    PGccController pController = NULL;
    PTwccManager pTwccManager = NULL;
    UINT32 totalPackets = 0, rtpSendCount = 0, twccFeedbackCount = 0;
    UINT32 minKbps = DEFAULT_MIN_KBPS;
    UINT32 initialKbps = DEFAULT_INITIAL_KBPS;
    UINT32 maxKbps = DEFAULT_MAX_KBPS;
    UINT8 twccExtId = DEFAULT_TWCC_EXT_ID;

    if (argc < 2) {
        printf("Usage: %s <pcap-file> [min-kbps] [initial-kbps] [max-kbps] [twcc-ext-id]\n", argv[0]);
        printf("  Defaults: %u / %u / %u / %u\n", DEFAULT_MIN_KBPS, DEFAULT_INITIAL_KBPS, DEFAULT_MAX_KBPS, DEFAULT_TWCC_EXT_ID);
        return 1;
    }

    if (argc >= 3) {
        minKbps = (UINT32) STRTOUL(argv[2], NULL, 10);
    }
    if (argc >= 4) {
        initialKbps = (UINT32) STRTOUL(argv[3], NULL, 10);
    }
    if (argc >= 5) {
        maxKbps = (UINT32) STRTOUL(argv[4], NULL, 10);
    }
    if (argc >= 6) {
        twccExtId = (UINT8) STRTOUL(argv[5], NULL, 10);
    }

    printf("GCC config: min=%u kbps, initial=%u kbps, max=%u kbps, twcc_ext_id=%u\n", minKbps, initialKbps, maxKbps, twccExtId);

    initKvsWebRtc();

    fp = fopen(argv[1], "rb");
    if (fp == NULL) {
        printf("ERROR: Cannot open file %s\n", argv[1]);
        retStatus = STATUS_OPEN_FILE_FAILED;
        goto CleanUp;
    }

    // Read and validate PCAP global header
    if (fread(globalHeader, 1, PCAP_GLOBAL_HEADER_SIZE, fp) != PCAP_GLOBAL_HEADER_SIZE) {
        printf("ERROR: Failed to read PCAP global header\n");
        retStatus = STATUS_INVALID_ARG;
        goto CleanUp;
    }

    if (globalHeader[0] != 0xD4 || globalHeader[1] != 0xC3 || globalHeader[2] != 0xB2 || globalHeader[3] != 0xA1) {
        printf("ERROR: Not a valid PCAP file (bad magic)\n");
        retStatus = STATUS_INVALID_ARG;
        goto CleanUp;
    }

    // Create TwccManager
    pTwccManager = (PTwccManager) MEMCALLOC(1, SIZEOF(TwccManager));
    CHK(pTwccManager != NULL, STATUS_NOT_ENOUGH_MEMORY);
    CHK_STATUS(hashTableCreateWithParams(TWCC_HASH_TABLE_BUCKET_COUNT, TWCC_HASH_TABLE_BUCKET_LENGTH, &pTwccManager->pTwccRtpPktInfosHashTable));

    // Create GCC controller
    GccConfig gccConfig;
    gccConfig.minBitrateBps = (UINT64) minKbps * 1000;
    gccConfig.maxBitrateBps = (UINT64) maxKbps * 1000;
    gccConfig.initialBitrateBps = (UINT64) initialKbps * 1000;
    CHK_STATUS(createGccController(&pController, &gccConfig));

    // Track pcap timestamps for pacing
    UINT64 firstPcapTimestampUs = 0;
    UINT64 firstWallClock = 0;
    BOOL firstPcapTimestamp = TRUE;

    // Read packets
    while (fread(recordHeader, 1, PCAP_RECORD_HEADER_SIZE, fp) == PCAP_RECORD_HEADER_SIZE) {
        UINT32 tsSec =
            (UINT32) recordHeader[0] | ((UINT32) recordHeader[1] << 8) | ((UINT32) recordHeader[2] << 16) | ((UINT32) recordHeader[3] << 24);
        UINT32 tsUsec =
            (UINT32) recordHeader[4] | ((UINT32) recordHeader[5] << 8) | ((UINT32) recordHeader[6] << 16) | ((UINT32) recordHeader[7] << 24);
        UINT64 pcapTimestampUs = (UINT64) tsSec * 1000000 + tsUsec;

        UINT32 inclLen =
            (UINT32) recordHeader[8] | ((UINT32) recordHeader[9] << 8) | ((UINT32) recordHeader[10] << 16) | ((UINT32) recordHeader[11] << 24);

        if (inclLen > 65535 + PCAP_TRANSPORT_HDR_SIZE) {
            printf("ERROR: Packet too large: %u\n", inclLen);
            break;
        }

        if (inclLen > packetBufSize) {
            SAFE_MEMFREE(pPacketBuf);
            packetBufSize = inclLen + 1024;
            pPacketBuf = (PBYTE) MEMALLOC(packetBufSize);
            CHK(pPacketBuf != NULL, STATUS_NOT_ENOUGH_MEMORY);
        }

        if (fread(pPacketBuf, 1, inclLen, fp) != inclLen) {
            break;
        }

        totalPackets++;

        if (inclLen < PCAP_TRANSPORT_HDR_SIZE) {
            continue;
        }

        PBYTE ipHeader = pPacketBuf + PCAP_ETHERNET_HDR_SIZE;
        UINT8 ipProtocol = ipHeader[9];
        if (ipProtocol != 0x11) {
            continue; // not UDP
        }

        PBYTE udpHeader = ipHeader + PCAP_IPV4_HDR_SIZE;
        UINT16 srcPort = ((UINT16) udpHeader[0] << 8) | udpHeader[1];
        UINT16 dstPort = ((UINT16) udpHeader[2] << 8) | udpHeader[3];

        UINT32 srcIp;
        MEMCPY(&srcIp, ipHeader + 12, 4);
        BOOL isSend = (srcIp == 0x0100000AU); // 10.0.0.1

        // Pace delivery according to pcap timestamps
        if (firstPcapTimestamp) {
            firstPcapTimestampUs = pcapTimestampUs;
            firstWallClock = GETTIME();
            firstPcapTimestamp = FALSE;
        } else {
            UINT64 pcapElapsedUs = pcapTimestampUs - firstPcapTimestampUs;
            UINT64 wallElapsed100ns = GETTIME() - firstWallClock;
            UINT64 wallElapsedUs = wallElapsed100ns / 10;
            if (pcapElapsedUs > wallElapsedUs) {
                UINT64 sleepUs = pcapElapsedUs - wallElapsedUs;
                if (sleepUs > 100) {
                    THREAD_SLEEP(sleepUs * 10);
                }
            }
        }

        // SEND RTP packets — track TWCC sequence numbers
        if (isSend && (srcPort == PCAP_FAKE_RTP_PORT || dstPort == PCAP_FAKE_RTP_PORT)) {
            PBYTE rtpData = pPacketBuf + PCAP_TRANSPORT_HDR_SIZE;
            UINT32 rtpLen = inclLen - PCAP_TRANSPORT_HDR_SIZE;

            if (rtpLen < 12) {
                continue;
            }

            PBYTE pRtpCopy = (PBYTE) MEMALLOC(rtpLen);
            if (pRtpCopy == NULL) {
                continue;
            }
            MEMCPY(pRtpCopy, rtpData, rtpLen);

            PRtpPacket pRtpPacket = NULL;
            retStatus = createRtpPacketFromBytes(pRtpCopy, rtpLen, &pRtpPacket);
            if (STATUS_FAILED(retStatus)) {
                MEMFREE(pRtpCopy);
                retStatus = STATUS_SUCCESS;
                continue;
            }

            if (pRtpPacket->header.extension && pRtpPacket->header.extensionProfile == TWCC_EXT_PROFILE) {
                PBYTE extData = findOneByteExtension(pRtpPacket->header.extensionPayload, pRtpPacket->header.extensionLength, twccExtId, NULL);
                if (extData != NULL) {
                    UINT16 twccSeqNum = getUnalignedInt16BigEndian(extData);

                    PTwccRtpPacketInfo pInfo = (PTwccRtpPacketInfo) MEMCALLOC(1, SIZEOF(TwccRtpPacketInfo));
                    if (pInfo != NULL) {
                        pInfo->localTimeKvs = pcapTimestampUs * 10; // us -> 100ns
                        pInfo->packetSize = rtpLen;
                        pInfo->remoteTimeKvs = TWCC_PACKET_UNITIALIZED_TIME;
                        hashTableUpsert(pTwccManager->pTwccRtpPktInfosHashTable, twccSeqNum, (UINT64) pInfo);
                        rtpSendCount++;
                    }
                }
            }

            freeRtpPacket(&pRtpPacket);
            continue;
        }

        // RECV RTCP packets — process TWCC feedback
        if (!isSend && (srcPort == PCAP_FAKE_RTCP_PORT || dstPort == PCAP_FAKE_RTCP_PORT)) {
            PBYTE rtcpData = pPacketBuf + PCAP_TRANSPORT_HDR_SIZE;
            UINT32 rtcpLen = inclLen - PCAP_TRANSPORT_HDR_SIZE;

            UINT32 rtcpOffset = 0;
            while (rtcpOffset + 4 <= rtcpLen) {
                UINT8 fmt = rtcpData[rtcpOffset] & 0x1F;
                UINT8 packetType = rtcpData[rtcpOffset + 1];
                UINT16 lengthWords = ((UINT16) rtcpData[rtcpOffset + 2] << 8) | rtcpData[rtcpOffset + 3];
                UINT32 packetBytes = ((UINT32) lengthWords + 1) * 4;

                if (packetBytes > rtcpLen - rtcpOffset) {
                    break;
                }

                // TWCC feedback: PT=205, FMT=15
                if (packetType == RTCP_PACKET_TYPE_GENERIC_RTP_FEEDBACK && fmt == RTCP_FEEDBACK_MESSAGE_TYPE_APPLICATION_LAYER_FEEDBACK) {
                    RtcpPacket rtcpPacket;
                    MEMSET(&rtcpPacket, 0, SIZEOF(RtcpPacket));

                    retStatus = setRtcpPacketFromBytes(rtcpData + rtcpOffset, packetBytes, &rtcpPacket);
                    if (STATUS_FAILED(retStatus)) {
                        retStatus = STATUS_SUCCESS;
                        goto nextRtcp;
                    }

                    retStatus = parseRtcpTwccPacket(&rtcpPacket, pTwccManager);
                    if (STATUS_FAILED(retStatus)) {
                        retStatus = STATUS_SUCCESS;
                        goto nextRtcp;
                    }

                    // Build TwccPacketReport array (same as onRtcpTwccPacket)
                    UINT16 baseSeqNum = pTwccManager->prevReportedBaseSeqNum;
                    UINT16 lastSeqNum = pTwccManager->lastReportedSeqNum;
                    UINT32 maxReports = (UINT32) ((UINT16) (lastSeqNum - baseSeqNum + 1));

                    if (maxReports > 0 && maxReports < 65536) {
                        PTwccPacketReport pReports = (PTwccPacketReport) MEMCALLOC(maxReports, SIZEOF(TwccPacketReport));
                        UINT32 reportCount = 0;

                        if (pReports != NULL) {
                            UINT16 seqNum;
                            for (seqNum = baseSeqNum; seqNum != (UINT16) (lastSeqNum + 1); seqNum++) {
                                UINT64 twccPktValue = 0;
                                if (STATUS_SUCCEEDED(hashTableGet(pTwccManager->pTwccRtpPktInfosHashTable, seqNum, &twccPktValue))) {
                                    PTwccRtpPacketInfo pTwccPacket = (PTwccRtpPacketInfo) twccPktValue;
                                    if (pTwccPacket != NULL) {
                                        pReports[reportCount].seqNum = seqNum;
                                        pReports[reportCount].sendTimeKvs = pTwccPacket->localTimeKvs;
                                        pReports[reportCount].arrivalTimeKvs = pTwccPacket->remoteTimeKvs;
                                        pReports[reportCount].packetSize = pTwccPacket->packetSize;
                                        pReports[reportCount].received = (pTwccPacket->remoteTimeKvs != TWCC_PACKET_LOST_TIME);
                                        reportCount++;
                                    }
                                }
                            }

                            if (reportCount > 0) {
                                UINT32 recvCount = 0;
                                UINT32 r;
                                for (r = 0; r < reportCount; r++) {
                                    if (pReports[r].received) {
                                        recvCount++;
                                    }
                                }

                                gccOnTwccPacketReports(pController, pReports, reportCount, 0);

                                UINT64 ackedBitrate = gccBitrateEstimatorGetBitrate(&pController->bitrateEstim);
                                DOUBLE timeSec = (DOUBLE) (pcapTimestampUs - firstPcapTimestampUs) / 1000000.0;
                                printf("TWCC t=%.3fs seq=[%u..%u] loss=%.3f recv=%u/%u "
                                       "m_hat=%.3f th=%.3f state=%-8s "
                                       "A_hat=%-6" PRIu64 " As_hat=%-6" PRIu64 " target=%-6" PRIu64 " acked=%-6" PRIu64 " kbps\n",
                                       timeSec, baseSeqNum, lastSeqNum, pController->currentLossRatio, recvCount, reportCount,
                                       pController->kalman.m_hat, pController->overuse.del_var_th, gccStateName(pController->rateCtrl.state),
                                       pController->rateCtrl.A_hat / 1000, pController->rateCtrl.As_hat / 1000,
                                       pController->rateCtrl.targetBitrate / 1000, ackedBitrate / 1000);
                                twccFeedbackCount++;
                            }

                            SAFE_MEMFREE(pReports);
                        }

                        // Clean up processed entries from hash table
                        UINT16 seqNum;
                        for (seqNum = baseSeqNum; seqNum != (UINT16) (lastSeqNum + 1); seqNum++) {
                            UINT64 v = 0;
                            if (STATUS_SUCCEEDED(hashTableGet(pTwccManager->pTwccRtpPktInfosHashTable, seqNum, &v))) {
                                PTwccRtpPacketInfo p = (PTwccRtpPacketInfo) v;
                                if (p != NULL && p->remoteTimeKvs != TWCC_PACKET_UNITIALIZED_TIME) {
                                    hashTableRemove(pTwccManager->pTwccRtpPktInfosHashTable, seqNum);
                                    MEMFREE(p);
                                }
                            }
                        }
                    }
                }

            nextRtcp:
                rtcpOffset += packetBytes;
            }
            continue;
        }
    }

    printf("\nSummary:\n");
    printf("  Total pcap packets:    %u\n", totalPackets);
    printf("  Sent RTP (with TWCC):  %u\n", rtpSendCount);
    printf("  TWCC feedbacks:        %u\n", twccFeedbackCount);
    printf("  Final target:          %" PRIu64 " kbps\n", gccGetTargetBitrate(pController) / 1000);
    printf("  Final loss ratio:      %.3f\n", gccGetLossRatio(pController));
    printf("  Final state:           %s\n", gccStateName(gccGetState(pController)));

CleanUp:
    if (pTwccManager != NULL) {
        if (pTwccManager->pTwccRtpPktInfosHashTable != NULL) {
            hashTableIterateEntries(pTwccManager->pTwccRtpPktInfosHashTable, 0, freeHashEntryValue);
            hashTableFree(pTwccManager->pTwccRtpPktInfosHashTable);
        }
        MEMFREE(pTwccManager);
    }

    freeGccController(&pController);
    SAFE_MEMFREE(pPacketBuf);
    if (fp != NULL) {
        fclose(fp);
    }
    deinitKvsWebRtc();

    if (STATUS_FAILED(retStatus)) {
        printf("ERROR: 0x%08x\n", retStatus);
        return 1;
    }
    return 0;
}
